const goats = [
  {
    id: 'goat1',
    name:'billy',
    disposition: 'rude',
    imageUrl: 'https://46yxb83hlyy77jig73dh02ok-wpengine.netdna-ssl.com/wp-content/uploads/2015/07/Cute-Goats-Photo-28.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat2',
    name:'bobby',
    disposition: 'nice',
    imageUrl: 'https://46yxb83hlyy77jig73dh02ok-wpengine.netdna-ssl.com/wp-content/uploads/2015/07/Cute-Goats-Photo-28.jpg',
    fullness: 67,
    favPose: 'warrior',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name:'barney',
    disposition: 'pugnacious',
    imageUrl: 'https://46yxb83hlyy77jig73dh02ok-wpengine.netdna-ssl.com/wp-content/uploads/2015/07/Cute-Goats-Photo-28.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name:'gruff',
    disposition: 'lazy',
    imageUrl: 'https://46yxb83hlyy77jig73dh02ok-wpengine.netdna-ssl.com/wp-content/uploads/2015/07/Cute-Goats-Photo-28.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: false,
    color: 'white',
  },
  {
    id: 'goat5',
    name:'belinda',
    disposition: 'rude',
    imageUrl: 'https://46yxb83hlyy77jig73dh02ok-wpengine.netdna-ssl.com/wp-content/uploads/2015/07/Cute-Goats-Photo-28.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
]

export default goats;